#!/usr/bin/env bash
# Find a GGUF under ~/AcouLM/models and write scripts/hpc/local_env.sh for CUDA.
# Usage:  bash scripts/hpc/configure_cuda_env.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${ROOT}/scripts/hpc/local_env.sh"
MODELS_DIR="${ROOT}/models"

echo "[configure] Looking for .gguf under ${MODELS_DIR} ..."

mapfile -t GGUFS < <(find "$MODELS_DIR" -name '*.gguf' -type f 2>/dev/null | sort)
if [[ ${#GGUFS[@]} -eq 0 ]]; then
  echo "[configure] No .gguf files found." >&2
  echo "  Download one first, e.g. into models/Qwen3.6-27B-gguf/" >&2
  exit 1
fi

GGUF="${GGUFS[-1]}"
if [[ ${#GGUFS[@]} -gt 1 ]]; then
  echo "[configure] Multiple GGUF files; using largest:"
  GGUF="$(du -b "${GGUFS[@]}" 2>/dev/null | sort -n | tail -1 | awk '{print $2}')"
  for f in "${GGUFS[@]}"; do
    echo "  - $f"
  done
  echo "[configure] Selected: $GGUF"
else
  echo "[configure] Found: $GGUF"
fi

LLAMA="${LLAMA_SERVER:-$HOME/llama.cpp/build/bin/llama-server}"
if [[ ! -x "$LLAMA" ]]; then
  LLAMA="$(command -v llama-server 2>/dev/null || true)"
fi
OV_DIR="${OPENVINO_GENAI_DIR:-$HOME/openvino_genai}"

mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
#!/usr/bin/env bash
# Generated by scripts/hpc/configure_cuda_env.sh — edit as needed.
export OPENVINO_GENAI_DIR=${OV_DIR}
export ACOULM_MODEL=${GGUF}
export ACOULM_DEVICE=GPU
export ACOULM_CUDA_DEVICES=\${ACOULM_CUDA_DEVICES:-0}
export LLAMA_SERVER=${LLAMA:-$HOME/llama.cpp/build/bin/llama-server}
export LLAMA_CTX=4096
export LLAMA_PARALLEL=1
export LLAMA_REASONING=off
export LLAMA_CACHE_RAM=0
EOF
chmod 600 "$ENV_FILE" 2>/dev/null || true

# Ensure cuda backend is selected
if [[ -f "${ROOT}/scripts/hpc/use_cuda_backend.sh" ]]; then
  bash "${ROOT}/scripts/hpc/use_cuda_backend.sh" >/dev/null
fi

echo "[configure] Wrote: $ENV_FILE"
echo "[configure] Run:"
echo "  source ${ENV_FILE}"
echo "  acoulm"
